# Generated by Django 5.0.1 on 2024-01-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='mini_description',
            field=models.CharField(default=1, max_length=155, verbose_name='мини описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='text1',
            field=models.TextField(default=1, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
