# Generated by Django 5.0.1 on 2024-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0002_about_mini_description_about_text1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=models.TextField(verbose_name='второй текст'),
        ),
    ]
