# Generated by Django 5.0.1 on 2024-01-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0003_alter_about_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='text2',
            field=models.TextField(default=1, verbose_name='второй текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=models.TextField(verbose_name='первый текст'),
        ),
    ]
