# Generated by Django 5.0.1 on 2024-01-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_about_text2_alter_about_text1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image3',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image4',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image5',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image6',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image7',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image8',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image9',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
