# Generated by Django 5.0.1 on 2024-01-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_glance_image_glance_title_delete_glanceinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glance',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='glance',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='glance',
            name='image2',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фотография сверху'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glance',
            name='image3',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фотография сверху'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glance',
            name='image4',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фотография сверху'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glance',
            name='image5',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фотография сверху'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glance',
            name='title2',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glance',
            name='title3',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glance',
            name='title4',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glance',
            name='title5',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
