# Generated by Django 4.0 on 2024-01-04 15:37

import ckeditor.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_alter_glance_descriptions_alter_glance_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image3',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image4',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image5',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image6',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image7',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image8',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image9',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=ckeditor.fields.RichTextField(verbose_name='первый текст'),
        ),
        migrations.AlterField(
            model_name='about',
            name='text2',
            field=ckeditor.fields.RichTextField(verbose_name='второй текст'),
        ),
        migrations.AlterField(
            model_name='art',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='color_image1/', verbose_name='Фото для рассветки 1 '),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='color_image2/', verbose_name='Фото  для рассветки 2'),
        ),
        migrations.AlterField(
            model_name='clothescolor',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='color_image3/', verbose_name='Фото  для рассветки 3'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='collectioninline',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='up_photo/', verbose_name='Фотография сверху'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_goods', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='glance',
            name='descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='glance',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='Фотография сверху'),
        ),
        migrations.AlterField(
            model_name='glance',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='Фотография сверху'),
        ),
        migrations.AlterField(
            model_name='glance',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография сверху'),
        ),
        migrations.AlterField(
            model_name='glance',
            name='image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография сверху'),
        ),
        migrations.AlterField(
            model_name='glance',
            name='image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография сверху'),
        ),
        migrations.AlterField(
            model_name='news',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='newsinline',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='news_image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='newsinline',
            name='mini_descriptions',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Мини описание'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='partner_image/', verbose_name='Фотография '),
        ),
        migrations.AlterField(
            model_name='style',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='styleinfo',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='mini_descriptions',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Мини описание'),
        ),
        migrations.AlterField(
            model_name='testimonialsinline',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='testimonials/image', verbose_name='Фото клиентов'),
        ),
        migrations.AlterField(
            model_name='testimonialsinline',
            name='testimonial',
            field=ckeditor.fields.RichTextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='trends',
            name='card_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='card_image/', verbose_name='Фото внутри карточки'),
        ),
        migrations.AlterField(
            model_name='trends',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='trends',
            name='first_descrip',
            field=ckeditor.fields.RichTextField(verbose_name='Главное описание'),
        ),
        migrations.AlterField(
            model_name='trends',
            name='goods',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='goods/trend/image', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='trends',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='trends_image/', verbose_name='Большое фото'),
        ),
    ]
