# Generated by Django 4.0 on 2024-01-04 15:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='slide_image', verbose_name='Фотография'),
        ),
    ]
